services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=4000
        - DATABASE_URL=file:dev.db
        - JWT_SECRET=secret
        - JWT_REFRESH_SECRET=refresh_secret
    container_name: nest_app
    ports:
      - "4000:4000"
    networks:
      - app_network

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_PORT=3000
        - VITE_API_BASE_URL=http://localhost:4000
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
